<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-05 at 16:55:51.
 * @group OOProgramming
 * @group ClosuresTest
 */
class ClosuresTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Closures
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Closures;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Closures::getClosure
     * @todo   Implement testGetClosure().
     */
    public function testGetClosure()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Closures::getClosureParam
     * @todo   Implement testGetClosureParam().
     */
    public function testGetClosureParam()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Closures::getClosureProperty
     * @todo   Implement testGetClosureProperty().
     */
    public function testGetClosureProperty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Closures::getClosurePropertyParam
     * @todo   Implement testGetClosurePropertyParam().
     */
    public function testGetClosurePropertyParam()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
