<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-05 at 15:23:17.
 * @group PHPBasics
 * @group DaughterTest
 */
class DaughterTest extends PHPUnit_Framework_TestCase
{

    protected $_daughter;

    public function setUp()
    {
        $this->_daughter = new \App\PHPBasics\Daughter();
    }

    public function tearDown()
    {
        unset($this->_daughter);
    }

    public function testDaughterInheritance()
    {
        $this->assertInstanceOf('\App\PHPBasics\Mother', $this->_daughter);
    }
    
    public function testNameSeting()
    {
        $this->_daughter->setName('Someone');
        $this->assertContains('Someone', $this->_daughter->getName());
    }

    /* nesse método testo a correta funcionalidade do método
     * sobrescrito do PHPUnit, tearDown();
     */
    public function testNameGetting()
    {
        $this->assertNull($this->_daughter->getName());
    }
}
