<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-05 at 10:12:15.
 */

/**
 * Classe de testes à classe OODaughter
 * @group OOProgramming
 * @group OODaughterTest
 * @author Thiago Mallon <thiagomallon@gmail.com>
 * @ignore
 * @codeCoverageIgnore
 */
class OODaughterTest extends PHPUnit_Framework_TestCase
{
    /**
     * Evitar erros no phpunit
     * @return void
     * @covers
     */
    public function testNotYet()
    {
        $this->markTestIncomplete('Not implemented');
    }
}
