<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-05 at 09:01:34.
 * @group OOProgramming
 * @group OOMotherTest
 */
class OOMotherTest extends PHPUnit_Framework_TestCase
{
    protected $_mother;

    public function setUp()
    {
        /* instancia classe, na propriedade $_mother */
        $this->_mother = new \App\OOProgramming\OOMother();
    }

    public function tearDown()
    {
        unset($this->_mother); // 'destroi' instância
    }
    
    public function testClassAlias()
    {
        $_localMother = new \App\OOProgramming\OOMother(); // cria instância da classe OOMother
        class_alias('\App\OOProgramming\OOMother', 'Father');
        $_father = new Father(); // cria instância via alias da classe OOMother
        $_stepFather = new Father(); // cria outra instância via alias da classe OOMother

        /* tests */
        $_localMother->setName('Davi'); // atribui valor à propriedade da classe
        $this->assertEquals('Davi', $_localMother->getName()); // verifica se valor da propriedade é o esperado
        $this->assertNotEquals('Davi', $_father->getName(), 'A instancia _father não recebe o valor
            atribuído à propriedade da instância _mother');
        /* verifica se a instancia $_father do alias Father, compartilha, por referência, as propriedades de $_localMother*/
        $_father->setName('Lilian'); // atribui valor à propriedade da classe
        $this->assertEquals('Lilian', $_father->getName()); // verifica valor atribuído
        $this->assertNotEquals('Lilian', $_stepFather->getName()); /* verifica se outra instancia do alias, compartilha,
                                                                    * por referência as propriedades da classe */
        /* verifica nomes das classes dos alias */
        $this->assertEquals('App\OOProgramming\OOMother', get_class($_father)); /* verifica se nome da classe
                                                                                             * é o nome original da classe, 
                                                                                             * não o alias */
        $this->assertNotEquals('Father', get_class($_stepFather)); /* verifica se nome da classe da instancia do alias é
                                                                    * diferente de Father */
        unset($_localMother);
        unset($_father);
        unset($_stepFather); // 'destroi' instancias
    }

    public function testDuplicatingInstance()
    {
        $_sister = $this->_mother; // cria nova instancia à partir de $this->_mother
        $this->_mother->setName('Yeshua'); // atribui valor à propriedade, através da instância $this->_mother
        /* verifica se instancia $_sister, teve propriedade name alterada, depois de alterar-se a mesma,
         * na instância $this->_mother */
        $this->assertEquals('Yeshua', $_sister->getName()); // a instancia não foi clonada é sim referenciada
    }

    public function testDestructingObject()
    {
        $_sister = $this->_mother; // cria nova instancia por referência
        $this->_mother->setName('Luke'); // atribui valor à propriedade
        
        unset($this->_mother); // 'destroi' instância, mas não o objeto
        $this->assertEquals('Luke', $_sister->getName()); // verifica-se que, de fato, objeto não foi destruído

        $_brother = $_sister->getInstance(); /* cria nova instância, desta vez, totalmente nova, não compartilha o
                                              * mesmo endereço de memória de $_sister */
        $this->assertNull($_brother->getName());   /* verifica-se que instância criada não possui a propriedade setada,
                                                    * pois consiste-se de uma nova instância */
        unset($_sister);
        unset($_brother); // 'destroi' instancias de objetos
    }

    public function testReturnArgsPassed()
    {
        // passa argumentos à função, para captura de array dos mesmos
        $args = $this->_mother->returnArgsPassed('first', 'second', 'third');
        $this->assertCount(3, $args); // verifica se array de retorno contém 3 elementos
        $this->assertContains('first', $args); // verifica se valor existe em qualquer dos elementos
    }

    public function testReturnObjVars()
    {
        $this->_mother->setName('The King David');
        $vars = $this->_mother->returnObjVars();
        /* valor retornado é resultado de chamada à função
         * get_object_vars(), como pode-se perceber, conseguimos acessar 
         * mesmo sendo essa protected.
         */
        $this->assertContains('The King David', $vars);
    }
}
