<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-05 at 11:58:43.
 * @group OOProgramming
 * @group ReflectingTest
 */
class ReflectingTest extends PHPUnit_Framework_TestCase
{

    protected $_classReflecting; // armazenará instância de Reflection
    protected $_objOnReflection; // armazenará instância da classe a ser testada pela API Reflection

    public function setUp()
    {
        $this->_objOnReflection = new \App\OOProgramming\Reflecting();
        $this->_classReflecting = new \ReflectionClass($this->_objOnReflection);
    }

    public function tearDown()
    {
        unset($this->_classReflecting);
    }

    public function testObjMethods()
    {
        // var_dump($this->_classReflecting->getMethods());
        // abaixo confirma existência de 5 métodos na classe
        $this->assertCount(5, $this->_classReflecting->getMethods());
    }

    public function testObjProperties()
    {
        // bloco abaixo testa se propriedade não vazia exibe valor - resultado negativo
        // $this->_objOnReflection->setRealLife('This is real!');
        // $this->_classReflecting = new \ReflectionClass($this->_objOnReflection);
        // var_dump($this->_classReflecting->getProperties());

        // abaixo confirma existência de 3 propriedades na classe
        $this->assertCount(3, $this->_classReflecting->getProperties());
    }
}
