<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-11 at 11:48:45.
 */

/**
 * @package Test\InputOutput
 */
namespace Test\InputOutput;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-11 at 11:48:45.
 * Classe implementa testes à objeto de FileManipulation
 * @group InputOutput
 * @group FileManipulationTest
 * @author Thiago Mallon <thiagomallon@gmail.com>
 */
class FileManipulationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FileManipulation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \App\InputOutput\FileManipulation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers App\InputOutput\FileManipulation::factoryFile
     * @todo   Implement testFactoryFile().
     */
    public function testFactoryFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
