<?php
namespace Test\InputOutput;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-16 at 14:29:12.
 */
class PageContentTakerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PageContentTaker
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PageContentTaker;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers App\InputOutput\PageContentTaker::takingWithGet
     * @todo   Implement testTakingWithGet().
     */
    public function testTakingWithGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
