<?php
namespace Test\InputOutput;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-10 at 23:55:24.
 */
class ResourceStreamTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ResourceStream
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \App\InputOutput\ResourceStream();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers App\InputOutput\ResourceStream::getTempStreamWrapper
     * @todo   Implement testGetTempStreamWrapper().
     */
    public function testGetTempStreamWrapper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\InputOutput\ResourceStream::writeOnTempStreamWrapper
     * @todo   Implement testWriteOnTempStreamWrapper().
     */
    public function testWriteOnTempStreamWrapper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
