<?php
namespace Test\DatabasesSQL;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-23 at 16:30:32.
 */
class SingWithTongueTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SingWithTongue
     */
    protected $conn;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        // $this->conn = \App\DatabasesSQL\SingWithTongue::connect(['dbms'=>'sqlite','host'=>'localhost','name'=>'sqlitest','user'=>'root', 'pass'=>'root']);
        $config = new \App\WebFeatures\ConfigsXMLReader();
        $sqlite = $config->getElementDataByAttr(['element'=>'database','attribute'=>'dbms','value'=>'sqlite']);
        $this->conn = \App\DatabasesSQL\SingWithTongue::connect(['dbms'=>'sqlite','name'=>$sqlite->name,'user'=>'root', 'pass'=>'root']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset($this->conn);
    }

    /**
     * The testConnect method
     * @return void
     */
    public function testConnect()
    {
        $this->assertInstanceOf('\App\DatabasesSQL\SingWithTongue', $this->conn);
        $this->assertInstanceOf('\PDO', $this->conn->dbh);
    }
}
